/* eslint-disable */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/watch.glb -o src/WatchModel1.jsx 
Author: gorzi (https://sketchfab.com/gorzi90)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/casio-edifice-watch-996400a75cf14ba59b338a8f1d63c7ab
Title: Casio Edifice watch
*/

import React, { useMemo, useEffect, useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import * as THREE from 'three'

export function Model({ accentColor = "#00e5ff", ...props }) {
  const hourRef = useRef();
  const minuteRef = useRef();
  const secondRef = useRef();

  useFrame(() => {
    const d = new Date();
    const h = d.getHours() % 12;
    const m = d.getMinutes();
    const s = d.getSeconds();
    const ms = d.getMilliseconds();
    
    const smoothS = s + ms / 1000;
    const smoothM = m + smoothS / 60;
    const smoothH = h + smoothM / 60;

    if (hourRef.current) hourRef.current.rotation.y = -smoothH * (Math.PI * 2) / 12;
    if (minuteRef.current) minuteRef.current.rotation.y = -smoothM * (Math.PI * 2) / 60;
    // The second hand has an inverted local Y axis due to its X/Z rotation (-PI/PI), so it needs positive rotation to tick clockwise.
    if (secondRef.current) secondRef.current.rotation.y = smoothS * (Math.PI * 2) / 60;
  });
  const { nodes, materials } = useGLTF('/watch.glb')

  const dynamicMaterial = useMemo(() => new THREE.MeshPhysicalMaterial({
    color: accentColor,
    metalness: 0.9,
    roughness: 0.25,
    envMapIntensity: 1.2,
    clearcoat: 0.1
  }), []);

  const glassMaterial = useMemo(() => new THREE.MeshPhysicalMaterial({
    color: '#ffffff',
    transmission: 1.0,
    opacity: 1,
    transparent: true,
    roughness: 0,
    ior: 1.5,
    thickness: 0.1,
    depthWrite: false,
    envMapIntensity: 1.5
  }), []);

  useEffect(() => {
    dynamicMaterial.color.set(accentColor);

    // Fix bezel (Material.012) and metal details from washing out
    if (materials['Material.012']) {
      materials['Material.012'].metalness = 0.5;
      materials['Material.012'].roughness = 0.3;
      materials['Material.012'].needsUpdate = true;
    }

    // Protect typical metal body parts with textures
    ['Material.001', 'Material.009'].forEach(matName => {
      if (materials[matName]) {
        materials[matName].metalness = 0.5;
        materials[matName].roughness = 0.3;
        materials[matName].needsUpdate = true;
      }
    });
  }, [accentColor, dynamicMaterial, materials]);

  return (
    <group {...props} dispose={null}>
      <group position={[0, -0.352, 0.732]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0.003, 0, 0.229]} rotation={[0, 0.001, 0]}>
            <mesh geometry={nodes.Object_4.geometry} material={materials['Material.001']} />
            <mesh geometry={nodes.Object_5.geometry} material={dynamicMaterial} />
          </group>
          <group position={[0, -0.007, 0]} scale={[0.014, 0.012, 0.038]}>
            <mesh geometry={nodes.Object_7.geometry} material={materials['Material.009']} />
            <mesh geometry={nodes.Object_8.geometry} material={dynamicMaterial} />
          </group>
          <group ref={hourRef} position={[-0.002, 0.014, -0.002]} rotation={[0, 0, 0]} scale={[0.024, 0.016, 0.024]}>
            <mesh geometry={nodes.Object_10.geometry} material={materials['Material.001']} />
            <mesh geometry={nodes.Object_11.geometry} material={dynamicMaterial} />
          </group>
          <group ref={secondRef} position={[-0.002, 0.014, -0.002]} rotation={[-3.14, 0, Math.PI]}>
            <mesh geometry={nodes.Object_13.geometry} material={dynamicMaterial} />
            <mesh geometry={nodes.Object_14.geometry} material={materials['Material.002']} />
          </group>
          <group ref={minuteRef} position={[-0.002, 0.014, -0.002]} rotation={[0, 0, 0]} scale={[0.024, 0.016, 0.024]}>
            <mesh geometry={nodes.Object_16.geometry} material={materials['Material.001']} />
            <mesh geometry={nodes.Object_17.geometry} material={dynamicMaterial} />
          </group>
          <group position={[0, -0.134, -0.754]} rotation={[-Math.PI, 0, -Math.PI]}>
            <mesh geometry={nodes.Object_33.geometry} material={materials['Material.004']} />
            <mesh geometry={nodes.Object_34.geometry} material={dynamicMaterial} />
          </group>
          <group position={[-0.213, -0.004, 0.008]} scale={[0.024, 0.016, 0.024]}>
            <mesh geometry={nodes.Object_36.geometry} material={materials['Material.001']} />
            <mesh geometry={nodes.Object_37.geometry} material={dynamicMaterial} />
          </group>
          <group position={[0.227, -0.002, 0.005]} rotation={[0, 1.017, 0]} scale={[0.024, 0.016, 0.024]}>
            <mesh geometry={nodes.Object_39.geometry} material={materials['Material.001']} />
            <mesh geometry={nodes.Object_40.geometry} material={dynamicMaterial} />
          </group>
          <group position={[0, -0.008, 0]} scale={0.438}>
            <mesh geometry={nodes.Object_66.geometry} material={materials['Material.006']} />
            <mesh geometry={nodes.Object_67.geometry} material={materials['Material.007']} />
            <mesh geometry={nodes.Object_68.geometry} material={materials['Material.010']} />
          </group>
          <group position={[0, 0.028, 0]} scale={[0.488, 0.42, 0.488]}>
            <mesh geometry={nodes.Object_72.geometry} material={materials.Material} />
            <mesh geometry={nodes.Object_73.geometry} material={materials.Material} />
          </group>
          <mesh geometry={nodes.Object_19.geometry} material={materials.Material} position={[0, -0.013, -0.592]} scale={[0.219, 0.105, 0.024]} />
          <mesh geometry={nodes.Object_21.geometry} material={materials.Material} position={[0, -0.013, 0.593]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.219, 0.105, 0.024]} />
          <mesh geometry={nodes.Object_23.geometry} material={materials.Material} position={[0.662, -0.065, -0.003]} rotation={[0, 0, -Math.PI / 2]} scale={0.063} />
          <mesh geometry={nodes.Object_25.geometry} material={materials.Material} position={[0.55, -0.061, -0.303]} rotation={[0, 0.496, -Math.PI / 2]} scale={0.06} />
          <mesh geometry={nodes.Object_27.geometry} material={materials.Material} position={[0.545, -0.061, 0.312]} rotation={[-Math.PI, 0.509, -Math.PI / 2]} scale={[-0.06, 0.06, 0.06]} />
          <mesh geometry={nodes.Object_29.geometry} material={materials.Material} position={[0.655, -0.053, 0.118]} rotation={[0, 0, -Math.PI / 2]} scale={0.047} />
          <mesh geometry={nodes.Object_31.geometry} material={materials.Material} position={[0.655, -0.053, -0.124]} rotation={[-Math.PI, 0, -Math.PI / 2]} scale={0.047} />
          <mesh geometry={nodes.Object_42.geometry} material={materials['Material.011']} position={[-0.002, 0.001, -0.235]} scale={[0.111, 0.111, 0.071]} />
          <mesh geometry={nodes.Object_44.geometry} material={materials['Material.009']} position={[-0.002, -0.013, -0.235]} scale={0.102} />
          <mesh geometry={nodes.Object_46.geometry} material={materials['Material.015']} position={[0, 0.001, -0.002]} />
          <mesh geometry={nodes.Object_48.geometry} material={materials['Material.016']} position={[0.003, 0.002, 0.229]} rotation={[0, -0.194, 0]} />
          <mesh geometry={nodes.Object_50.geometry} material={materials['Material.016']} position={[-0.213, -0.002, 0.008]} />
          <mesh geometry={nodes.Object_52.geometry} material={materials['Material.016']} position={[0.226, 0.001, 0.006]} scale={0.955} />
          <mesh geometry={nodes.Object_54.geometry} material={materials['Material.016']} position={[0.226, 0.005, 0.006]} scale={0.984} />
          <mesh geometry={nodes.Object_60.geometry} material={materials.Material} position={[0.014, -1.032, -0.22]} rotation={[-2.972, 0, 0]} scale={0.108} />
          <mesh geometry={nodes.Object_62.geometry} material={materials['Material.013']} position={[0, -0.136, 0]} rotation={[0, 0.442, 0]} />
          <mesh geometry={nodes.Object_64.geometry} material={materials['Material.004']} position={[0, -0.976, -0.455]} rotation={[0.103, 0, 0]} scale={[0.322, 0.061, 0.061]} />
          <mesh geometry={nodes.Object_70.geometry} material={materials['Material.001']} position={[0, -0.002, 0]} scale={[0.438, 0.377, 0.438]} />
          <mesh geometry={nodes.Object_75.geometry} material={materials['Material.012']} position={[0, 0.028, 0]} />
          <mesh geometry={nodes.Object_77.geometry} material={materials['Material.005']} position={[0, -0.002, 0]} />
          <mesh geometry={nodes.Object_79.geometry} material={materials['Material.016']} position={[0, -0.008, 0]} />
          <mesh geometry={nodes.Object_81.geometry} material={glassMaterial} position={[0, 0.028, 0]} scale={1.011} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/watch.glb')